services:
  #Database
  amelia_db:
    image: mariadb:11.3.2
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: wordpress
    container_name: amelia_db
  #Web
  amelia_wp:
    depends_on:
      - amelia_db
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8079:80
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: amelia_db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: wp_
    container_name: amelia_wp
    volumes:
      - ./wp-content:/var/www/html/wp-content
  #PhpMyAdmin
  amelia_myadmin:
    image: phpmyadmin:latest
    container_name: amelia_myadmin
    restart: always
    ports:
      - 4999:80
    environment:
      PMA_HOST: amelia_db
      UPLOAD_LIMIT: 100M
    depends_on:
      - amelia_db
volumes:
  db_data:
  wp-content:
